### ISSUE TITLE
const LuaGlueClass::method does not compile

### ISSUE THREAD

**Issue by JMLX42** [Tomasu/LuaGlue#13]
Commit a31268d4cb8324ceb28e83c74e508f901361ce51 does not compile with GCC 4.8.1:

<pre>
template<typename... _Args>
LuaGlueClass<_Class> &method(const std::string &name, void (_Class::*fn)(_Args...))
{
// ...
}
        
template<typename... _Args>
LuaGlueClass<_Class> &method(const std::string &name, void (_Class::*fn)(_Args...) const)
{
// ...
}
</pre>

<pre>
lib/LuaGlue/include/LuaGlue/LuaGlueClass.h:251:25: error: ‘template<class _Ret, class ... _Args> LuaGlueClass<_Class>& LuaGlueClass<_Class>::method(const string&, _Ret (_Class::*)(_Args ...)const) [with _Ret = _Ret; _Args = {_Args ...}; _Class = const std::basic_string<char>]’ cannot be overloaded
   LuaGlueClass<_Class> &method(const std::string &name, _Ret (_Class::*fn)(_Args...) const)
                         ^
lib/LuaGlue/include/LuaGlue/LuaGlueClass.h:241:25: error: with ‘template<class _Ret, class ... _Args> LuaGlueClass<_Class>& LuaGlueClass<_Class>::method(const string&, _Ret (_Class::*)(_Args ...)) [with _Ret = _Ret; _Args = {_Args ...}; _Class = const std::basic_string<char>]’
   LuaGlueClass<_Class> &method(const std::string &name, _Ret (_Class::*fn)(_Args...))
</pre>

The problem is in the fact that the constness of the function pointer is not enough to allow the overload.
According to §13.1 of the standard:

<pre>
Parameter declarations that differ only in the presence or absence of const and/or volatile are equivalent. That is, the const and volatile type-specifiers for each parameter type are ignored [...]
</pre>

Did you really manage to compile this part? One of the fixes would be to separate method() and constMethod() methods. What do you think?

**Comment by Tomasu** [comment]
It compiles fine in 4.8.2. Interesting. Check out foo.cpp. Yeah, if according to the standard, the const method() should be renamed to constMethod().

**Comment by JMLX42** [comment]
Wow that's strange indeed...

**Comment by JMLX42** [comment]
Also LuaGlueObject.h does not "compile" because of LuaGlueObjectImpl::vget() returns a void \* when it is expected to return a const void\* when _Class is a const "something".

**Comment by Tomasu** [comment]
Hm, yeah, that makes sense. have to cast that or something.

**Comment by JMLX42** [comment]
const_cast won't work at 100% because some times are not usable with const_cast. I tried to have different overload of vget() using std::enable_if and std::is_const but it doesn't work.

Simply changing

<pre>
typedef _Class Type;
</pre>

into:

<pre>
typedef std::remove_const<_Class> Type;
</pre>

everywhere in LuaGlueObject.h won't work either.

I think that in general you should use std::remove_const on all your templates: it's ok for objects to get const values when the template is the corresponding non-const type. It doesn't work the other way around, which is why we have so much trouble...

**Comment by Tomasu** [comment]
Are you doing anything special to compile it? Adding any extra flags?

**Comment by JMLX42** [comment]
Nope... doesn't compile...
I changed LuaGlueClass.method into LuaGlueClass.constMethod when relevant.
But then I got that LuaGlueObject problem.

**Comment by JMLX42** [comment]
I think I'll add a constness example you can build/test against. How does that sound?

**Comment by Tomasu** [comment]
Yeah, I think that'd be useful.

**Comment by Tomasu** [comment]
Also, have you updated your remaining pull requests?

**Comment by JMLX42** [comment]
For some reasons your examples compile fine... but my code does not.
I'm still investigating.

**Comment by Tomasu** [comment]
I'm going to assume this has been solved. Please re open if not.
